apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-data-generator.fullname" . }}-http
  annotations:
    {{- toYaml .Values.http.annotations | nindent 4 }}
  labels:
    {{- include "prometheus-data-generator.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  replicas: {{ toYaml .Values.http.replicaCount }}
  selector:
    matchLabels:
      {{- include "prometheus-data-generator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: http
  template:
    metadata:
      annotations:
        {{- toYaml .Values.http.podAnnotations | nindent 8 }}
      labels:
        {{- include "prometheus-data-generator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: http
    spec:
      containers:
      - name: prometheus-data-generator
        image: {{ toYaml (print .Values.image.repository ":" .Values.image.tag) }}
        imagePullPolicy: {{ toYaml .Values.image.pullPolicy }}
        env:
        - name: PDG_CONFIG
          value: /pdg/config.yml
        ports:
        - name: http
          containerPort: 9000
        lifecycle:
          {{- toYaml .Values.http.lifecycle | nindent 10 }}
        resources:
          {{- toYaml .Values.http.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /pdg
      affinity:
        {{- toYaml .Values.http.affinity | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.http.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.http.tolerations | nindent 8 }}
      volumes:
      - name: config
        configMap:
          name: {{ include "prometheus-data-generator.fullname" . }}-config
